# Generated by Django 5.0.2 on 2024-02-12 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_app', '0002_remove_advisor_thesis'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='thesis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='thesis_app.thesis'),
        ),
    ]
