# Generated by Django 5.0.2 on 2024-02-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_app', '0003_advisor_thesis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='publish',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
